export const articleList = [
  {id: 1, title: "Screwtape letters", author: "C. S. Lewis", content: "The Screwtape Letters is a Christian apologetic novel by C. S. Lewis and dedicated to J. R. R. Tolkien. It is written in a satirical, epistolary style and, while it is fictional in format, the plot and characters are used to address Christian theological issues, primarily those to do with temptation and resistance to it.\nFirst published in February 1942,[2] the story takes the form of a series of letters from a senior demon, Screwtape, to his nephew, Wormwood, a junior tempter. The uncle's mentorship pertains to the nephew's responsibility in securing the damnation of a British man known only as \"the Patient\"."},
  {id: 2, title: "Four loves (with UTM Params)", author: "C. S. Lewis", content: "The Four Loves is a 1960 book by C. S. Lewis which explores the nature of love from a Christian and philosophical perspective through thought experiments.[1] The book was based on a set of radio talks from 1958 which had been criticised in the U.S. at the time for their frankness about sex.", utm:"/?campaign=facebook&user=usr4345&loggedIn=false"},
  {id: 3, title: "The problem of pain by C.S. Lewis", author: "C. S. Lewis", content: "The Problem of Pain is a 1940 book on the problem of evil by C. S. Lewis, in which Lewis argues that human pain, animal pain, and hell are not sufficient reasons to reject belief in a good and powerful God.\n" +
      "Lewis states that his writing is \"not primarily arguing the truth of Christianity but describing its origin - a task ... necessary if we are to put the problem of pain in its right setting\".[1] He begins by addressing the flaws in common arguments against the belief in a just, loving, and all-powerful God such as: \"If God were good, He would make His creatures perfectly happy, and if He were almighty He would be able to do what he wished. But the creatures are not happy. Therefore God lacks either goodness, or power, or both.\"[2] Topics include human suffering and sinfulness, animal suffering, and the problem of hell, and seeks to reconcile these with an omnipotent force beyond ourselves."},
  {id: 4, title: "The Lion, the Witch and the Wardrobe by C.S. Lewis", author: "C. S. Lewis",  content: "The Lion, The Witch and the Wardrobe by C.S. Lewis is a classic children's fantasy novel that takes readers on a magical journey through a wardrobe into the enchanting world of Narnia where four siblings must battle the evil witch and restore the rightful ruler to the throne."},
  {id: 5, title: "Prince Caspian by C.S. Lewis", author: "C. S. Lewis", content: "Prince Caspian is a captivating fantasy novel by C.S. Lewis. Join the Pevensie siblings as they return to Narnia to help Prince Caspian reclaim his rightful throne and restore peace to the magical land."},
  {id: 6, title: "The weight of Glory by C.S. Lewis", author: "C. S. Lewis", content: "The Weight of Glory by C.S. Lewis is a collection of inspiring essays that explore the concept of glory and how it relates to our spiritual journey. It offers profound insights into the human longing for something greater and the significance of our everyday actions."}
]
